apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
  ##
  ## Rules for the operator
  ##
  - apiGroups: ["apiextensions.k8s.io"]
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - update
      - patch

  - apiGroups: ["config.nri"]
    resources:
      - nriplugindeployments
      - nriplugindeployments/status
      - nriplugindeployments/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch

  - apiGroups: ["topology.node.k8s.io"]
    resources:
      - noderesourcetopologies
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for rbac.authorization.k8s.io
  ##
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      - clusterrolebindings
      - clusterroles
      - rolebindings
      - roles
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - namespaces
      - secrets
      - serviceaccounts
      - pods
      - pods/exec
      - pods/log
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for core API group (e.g., con
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - config.nri
    resources:
      - balloonspolicies
      - balloonspolicies/status
    verbs:
      - get
      - list
      - watch
      - get
      - update
      - patch
      - create
