---
- name: Add nri-plugins helm chart repo
  kubernetes.core.helm_repository:
    name: nri-plugins
    repo_url: "https://containers.github.io/nri-plugins"

- name: Deploy balloons plugin
  kubernetes.core.helm:
    name: balloons
    chart_ref: nri-plugins/nri-resource-policy-balloons
    release_namespace: kube-system
    chart_version: v0.10.0
    create_namespace: True
    skip_crds: True
    atomic: true
    update_repo_cache: true
    kubeconfig: /opt/ansible/.kube/config
  when:
  # - state == "present"
  - pluginName in ["topology-aware", "balloons", "memory-qos", "memtierd", "sgx-epc"]

# - name: Uninstall {{ pluginName }} plugin
#   kubernetes.core.helm:
#     name: "{{ pluginName }}"
#     namespace: "{{ ansible_operator_meta.namespace }}"
#     state: absent
#   when: state == "absent" or state == "revoked"
